(deftheme raven
  "Created 2020-11-07.")

(custom-theme-set-faces
 'raven
 '(default ((t (:family "Fira Code" :foundry "CTDB" :width normal :height 150 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#8898a9" :background "#192129" :stipple nil :inherit nil))))
 '(cursor ((((background light)) (:background "black")) (((background dark)) (:background "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#c4dde8"))))
 '(highlight ((t (:foreground "#192129" :background "#c4dde8"))))
 '(region ((t (:extend t :foreground "#192129" :background "#c4dde8"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:extend t :foreground "#192129" :background "#729fcf"))))
 '(trailing-whitespace ((t (:background "#ff8683"))))
 '(font-lock-builtin-face ((t (:foreground "#8898a9" :weight bold))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "grey40"))))
 '(font-lock-constant-face ((t (:foreground "#a6a1ea"))))
 '(font-lock-doc-face ((t (:foreground "grey50"))))
 '(font-lock-function-name-face ((t (:weight bold :foreground "#729fcf"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "#c4dde8"))))
 '(font-lock-negation-char-face ((t (:weight normal :foreground "#e9b96e"))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:weight normal :foreground "#649d8a"))))
 '(font-lock-type-face ((t (:foreground "#e9b96e"))))
 '(font-lock-variable-name-face ((t (:foreground "#c4dde8"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ff8683"))))
 '(button ((t (:inherit (link)))))
 '(link ((((class color) (min-colors 88) (background light)) (:underline (:color foreground-color :style line) :foreground "RoyalBlue3")) (((class color) (background light)) (:underline (:color foreground-color :style line) :foreground "blue")) (((class color) (min-colors 88) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan1")) (((class color) (background dark)) (:underline (:color foreground-color :style line) :foreground "cyan")) (t (:inherit (underline)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#090c10"))))
 '(header-line ((t (:box nil :foreground "#c4dde8" :background "#243248"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:foreground "#c4dde8" :background "#2A3A53"))))
 '(mode-line-buffer-id ((t (:foreground "#d2dde8"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 1 :color "#090c10" :style released-button)))))
 '(mode-line-inactive ((t (:weight light :box (:line-width -1 :color "#090c10" :style nil) :foreground "#8898a9" :background "#090c10"))))
 '(isearch ((t (:foreground "#880e4f" :background "#ff80ab"))))
 '(isearch-fail ((t (:foreground "#b71c1c" :background "#ff8683"))))
 '(lazy-highlight ((t (:weight bold :foreground "#192129" :background "#729fcf"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "yellow1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'raven)
