(deftheme spacegray-easy
  "Created 2020-11-01.")

(custom-theme-set-faces
 'spacegray-easy
 '(cursor ((t (:background "#DCA432"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#89AAEB"))))
 '(highlight ((t (:inverse-video nil :background "#343d46"))))
 '(region ((t (:extend t :background "azure4" :foreground "#232830"))))
 '(shadow ((t (:foreground "#4f5b67"))))
 '(secondary-selection ((t (:extend t :background "#bf616a"))))
 '(trailing-whitespace ((t (:underline nil :inverse-video t :foreground "#bf616a"))))
 '(font-lock-builtin-face ((t (:foreground "LightCoral"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#4f5b67"))))
 '(font-lock-comment-face ((t (:foreground "dark olive green"))))
 '(font-lock-constant-face ((t (:foreground "#B4EB89"))))
 '(font-lock-doc-face ((t (:foreground "sea green"))))
 '(font-lock-function-name-face ((t (:foreground "#DCA432"))))
 '(font-lock-keyword-face ((t (:foreground "#89AAEB"))))
 '(font-lock-negation-char-face ((t (:foreground "#89AAEB"))))
 '(font-lock-preprocessor-face ((t (:foreground "gold"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#ebcb8b"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#C189EB"))))
 '(font-lock-string-face ((t (:foreground "burlywood"))))
 '(font-lock-type-face ((t (:foreground "CadetBlue1"))))
 '(font-lock-variable-name-face ((t (:foreground "#ebcb8b"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#bf616a"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#232830"))))
 '(header-line ((t (:foreground "#C189EB" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "systeminfotext" :background "systeminfowindow" :inherit (variable-pitch)))))
 '(mode-line ((t (:family "Lucida Grande" :foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((t (:foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#ffffff"))))
 '(mode-line-highlight ((t (:box nil :foreground "#C189EB"))))
 '(mode-line-inactive ((t (:weight normal :box nil :foreground "#a7adba" :background "#1c1f26" :inherit (mode-line)))))
 '(isearch ((t (:foreground "#ebcb8b" :background "#343d46"))))
 '(isearch-fail ((t (:inverse-video t :background "#232830" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:background "paleturquoise4")) (((class color) (min-colors 16)) (:background "turquoise3")) (((class color) (min-colors 8)) (:background "turquoise3")) (t (:underline (:color foreground-color :style line)))))
 '(match ((t (:inverse-video nil :foreground "#ebcb8b" :background "#343d46"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:inherit nil :extend nil :stipple nil :background "#232830" :foreground "gray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 151 :width normal :foundry "outline" :family "Consolas")))))

(provide-theme 'spacegray-easy)
